### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tuffboy807** [NightfallGT/Discord-Account-Generator#1]
Finally got it to show me the discord generator stuff and now whenever I do it, it fails to verify it and I can't login with the accounts created

**Comment by NightfallGT** [comment]
What's your discord?

**Comment by tuffboy807** [comment]
> What's your discord? Do you get any errors?

Cloudy#0426 is my discord, I have found another tool but it doesn't include threading, I can run it however I did have to uninstall bs4 and then reinstall it, then I got to the discord gen and it gets past setting up, doesn't show the captcha on the window I have tried upgrading to my chrome version didn't work or show it found the other tool it worked with out me upgrading it but was similir so I decided to downgrade the chromedriver this time to the one provided that didn't work as in show the captcha nor auto verify the email
