### ISSUE TITLE
Feature request, automatically get token of created account by doing this

### ISSUE THREAD

**Issue by cuj** [NightfallGT/Discord-Account-Generator#10]
so I found an easier way (without going to LocalStorage) of getting token of created account by pasting the following code in "Console" tab in inspect element while on discord
```js
var req=webpackJsonp.push([[],{extra_id:(e,r,t)=>e.exports=t},[["extra_id"]]]);for(let e in req.c)if(req.c.hasOwnProperty(e)){let r=req.c[e].exports;if(r&&r.__esModule&&r.default)for(let e in r.default)"getToken"==e&&console.log(r.default.getToken())}
```
[Credits to rezizt for figuring the code out](https://github.com/6uv/console-hacks/blob/master/Get%20token.txt)
I believe it's javascript code, maybe the code can automatically run and then the token can be written in a text file.

**Comment by Nuture-blip** [comment]
Hey, i have implemented this  to NightFalls code using py2js but it cuts out the last 6 lines of the account token

**Comment by PiggyAwesome** [comment]
> Hey, i have implemented this to NightFalls code using py2js but it cuts out the last 6 lines of the account token

can you share the code?

**Comment by Sarlay** [comment]
Hi,
I also implemented that feature but in a different way (only using selenium).
`self.localStorage = self.driver.execute_script("let popup; popup = window.open('', '', `width=1,height=1`); if(!popup || !popup.document || !popup.document.write) console.log('Please allow popups'); window.dispatchEvent(new Event('beforeunload')); token = popup.localStorage.token.slice(1, -1); popup.close(); return token")`

The token is now stored inside the self.localStorage variable
hope that helps

**Comment by freedomshare** [comment]
@SARLAY  could you help me add this my email is cyber4hits@gmail.com
