### ISSUE TITLE
Webdriver Error when i use a Proxy

### ISSUE THREAD

**Issue by TheT0fu** [NightfallGT/Discord-Account-Generator#5]
When I run the script with a proxy, I get a webdriver error. As in the README, I checked my Chrome version and downloaded the appropriate chromedriver. Didn't do anything unfortunately. The proxies are also all working and should work.

![01-03-2021_13-55-22](https://user-images.githubusercontent.com/24474449/109499916-cfcd8300-7a95-11eb-9e34-a5db497553e0.png)

Without proxy the script runs fine. 

Cheers.

**Comment by macios123** [comment]
I think it's because of the proxy, not a bad implementation.
What proxy are you using?

**Comment by TheT0fu** [comment]
Sorry for the late reply.
It was actually due to a couple of proxy servers not working properly. I tried again with working and then everything worked. Thank you.

Cheers.
