### ISSUE TITLE
-

### ISSUE THREAD

**Issue by cuj** [NightfallGT/Discord-Account-Generator#57]
>

**Comment by tnv1r** [comment]
This is because they added a cloudflare page, it must be a simple fix. Dunno what happens.

**Comment by EOSonGameboy** [comment]
import cfscrape

scraper = cfscrape.create_scraper()  # returns a CloudflareScraper instance
# Or: scraper = cfscrape.CloudflareScraper()  # CloudflareScraper inherits from requests.Session
print scraper.get("http://somesite.com").content  # => "<!DOCTYPE html><html><head>..."

**Comment by EOSonGameboy** [comment]
https://github.com/Anorov/cloudflare-scrape

**Comment by bigdemonxl** [comment]
> https://github.com/Anorov/cloudflare-scrape



> import cfscrape
> 
> scraper = cfscrape.create_scraper() # returns a CloudflareScraper instance
> 
> # Or: scraper = cfscrape.CloudflareScraper() # CloudflareScraper inherits from requests.Session
> print scraper.get("[http://somesite.com").content](http://somesite.com%22).content) # => "..."

Don't work, can you help me ?

**Comment by Aritz331** [comment]
nope xd
