### ISSUE TITLE
Hey pls make me other gen

### ISSUE THREAD

**Issue by vuthanhtrung2010** [NightfallGT/Discord-Account-Generator#87]
Your gen is good but i got captcha key and proxies! Pls make me a gen using captcha key and proxies and no chrome driver require (i just need python use 2 captcha) and using gmailnator like your tool here too.

**Comment by Az-r08** [comment]
we can't understand you wdym by that

**Comment by arin2115** [comment]
Bruh, firstly you have to understand how Discord works. Using brain you'll know that it's impossible to use gmailnator because it's detected already...
